config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'themes#index'
  get 'tweets/search'
  resources :tweets do
    resources :themes, only: [:index]
    resources :comments, only: :create
  end

  resources :baggages, only: [:index, :new]
  resources :users, only: :show
end

app/models/theme.rb
class Theme < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'The Best Mountain ' },
    { id: 3, name: 'これが俺の山ごはん' },
    { id: 4, name: 'Mountain Wear' },
    { id: 5, name: 'これを見たら行きたくなる絶景スポット' }
  ]

  include ActiveHash::Associations
  has_many :tweets
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  before_action :search_tweet, only: [:index]

  
  def index
    @tweets = Tweet.all
  end

  def new
  end
  

  private

  def search_tweet
    @p = Tweet.ransack(params[:q])
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/index.html.erb
<div class='title-contents'>
    <h2 class='service-title'>
      Get to know the mountains and enjoy them

    </h2>
    <p class='service-explain'>
      「山を知り、山を楽しむ」非日常な体験を存分に楽しむためのアプリケーション
    </p>

<div class='theme-contents'>
<p class='bestmountain-title'>
      テーマ投稿一覧

    </p>
        <%= search_form_for @p, url: tweets_path do |f| %>
        <%= f.collection_select :theme_id_eq, Theme.where.not(id:1), :id, :name,  include_blank: '選択して下さい' %>
        <br>
        <%= f.submit '検索' %>
       <% end %>
    <ul class='theme-lists'>
      <li class='list'>
      <%= link_to(tweets_path, class: 'list-pict') do %>
        <div class='list-pict-content'>
        <%= image_tag "theme1.jpg", class:"list-pict" %>
      <% end %>
      </a>  
      </li>
      <li class='list'>
      <%= link_to(tweets_path, class: 'list-pict') do %>
        <div class='list-pict-content'>
        <%= image_tag "theme2.jpg", class:"list-pict" %>
      <% end %>
      </li>
      <li class='list'>
      <%= link_to(tweets_path, class: 'list-pict') do %>
        <div class='list-pict-content'>
        <%= image_tag "theme3.jpg", class:"list-pict" %>
      <% end %>
      </li>
      <li class='list'>
      <%= link_to(tweets_path, class: 'list-pict') do %>
        <div class='list-pict-content'>
        <%= image_tag "theme4.jpg", class:"list-pict" %>
      <% end %>
      </li>
    </ul>

    <p class='bestmountain-title'>
      気になる山のレビューをチェックする

    </p>
        <%= search_form_for @p, url: tweets_search_path do |f| %>
        <%= f.collection_select :mountain_name_id_eq, MountainName.where.not(id:1), :id, :name,  include_blank: '選択して下さい' %>
        <br>
        <%= f.submit '検索' %>
       <% end %>
      </li>
    <p class='bestmountain-title'>
      YamaShiruおすすめの山情報

    </p>

    <table>
  <tr>
    <th>山の情報</th>
    <th>登山時間</th>
    <th>眺望度</th>
    <th>体力度</th>
    <th>危険度</th>
  </tr>
  <tr>
    <td>富士山</td>
    <td>6：00</td>
    <td>★★★</td>
    <td>★★</td>
    <td>★★★</td>
  </tr>
  <tr>
    <td>高尾山</td>
    <td>2：00</td>
    <td>★</td>
    <td>★</td>
    <td>★</td>
  </tr>
  <tr>
    <td>金時山</td>
    <td>4：00</td>
    <td>★★</td>
    <td>★★</td>
    <td>★★</td>
  </tr>
  <tr>
    <td>塔ノ岳</td>
    <td>6：00</td>
    <td>★★</td>
    <td>★★</td>
    <td>★★★</td>
  </tr>
  <tr>
    <td>御岳山</td>
    <td>5：00</td>
    <td>★★</td>
    <td>★★★</td>
    <td>★★★</td>
  </tr>
  </table>
</div>

<%= link_to(new_baggage_path, class: "baggage-btn") do %>
  <%= image_tag 'logo.png' , size: '185x50' ,class: "baggage-btn-icon" %>
<% end %>