config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'themes#index'
  get 'tweets/search'
  resources :tweets do
    resources :themes, only: [:index]
    resources :comments, only: :create
  end

  resources :baggages, only: [:index, :new]
  resources :users, only: :show
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :theme
  belongs_to :prefecture
  belongs_to_active_hash :mountain_name
  belongs_to :climbing_time
  belongs_to :mountain_view
  belongs_to :stamina
  belongs_to :danger

  has_many :comments, dependent: :destroy

  has_one_attached :image

  validates :title, :image, presence: true
  with_options numericality: { other_than: 1, message: "can't be blank"} do
  validates :theme_id
  validates :prefecture_id
  validates :mountain_name_id
  end
  belongs_to :category, optional: true 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_tweet, only: [:edit, :show, :update]
  before_action :search_tweet, only: [:index, :search]
  before_action :move_to_index, except: [:index, :show, :new, :create, :search]

  def index
    #@tweets = Tweet.where(theme_id: '1')
    @tweets = Tweet.order("created_at DESC")
    @results = @p.result.includes(@tweet)
    set_tweet_column
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @tweet.comments.includes(:user)
  end

  def search
    @results = @p.result.includes(@tweet)
  end

  def edit
  end

  def update
    @tweet.update(tweet_params)
    if @tweet.save
      redirect_to tweet_path
    else
      render :edit
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end


  private

  def tweet_params
    params.require(:tweet).permit(:image, :title, :theme_id, :prefecture_id, :mountain_name_id, :climbing_time_id, :mountain_view_id, :stamina_id, :danger_id).merge(user_id: current_user.id)
  end

  def search_tweet
    @p = Tweet.ransack(params[:q])
  end

  def set_tweet_column
    @tweet_name = Tweet.select("name").distinct  
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    @tweet = Tweet.find(params[:id])
    unless user_signed_in? && current_user.id == @tweet.user_id
      redirect_to action: :index
  end

 end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= form_with(model: @tweet, local: true) do |f| %>
    <h2>1.写真【必須】</h2>
      <%= f.file_field :image, id:"tweet-image", placeholder: "Image Url" %>
    <h2>2.写真のタイトルを記入ください【必須】</h2>
      <%= f.text_field :title, placeholder: "Title" %>
    <h2>3.テーマを選択してください【必須】</h2>
      <%= f.collection_select(:theme_id, Theme.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>4.登山を開始した地域を選択してください【必須】</h2>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>5.登山した山の情報を選択してください【必須】</h2>
      <%= f.collection_select(:mountain_name_id, MountainName.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>6.登山時間を選択してください</h2>
      <%= f.collection_select(:climbing_time_id, ClimbingTime.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>7.体力度を選択してください</h2>
      <%= f.collection_select(:stamina_id, Stamina.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>8.眺望度を選択してください</h2>
      <%= f.collection_select(:mountain_view_id, MountainView.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>9.危険度を選択してください</h2>
      <%= f.collection_select(:danger_id, Danger.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>

    <h2></h2>
      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<% if @results.length !=0 %>
  
  <% @results.each do |tweet| %>
  <%= link_to(tweet_path(tweet.id), class: 'tweet-img') do %>
  <%= image_tag tweet.image.variant(resize: '500x500'), class: "tweet-img" %>
  <% end %>
  <% end %>
<% else %>
  該当する投稿はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>

<%#div class='wrapper' %>
<%# @tweets.each do |tweet| %>
    <%#= link_to(tweet_path(tweet.id), class: 'tweet-img') do %>
    <%#= image_tag tweet.image.variant(resize: '500x500'), class: "tweet-img" %>
<%# end %>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @tweet, local: true) do |f| %>
    <h2>1.写真</h2>
      <%= f.file_field :image, id:"tweet-image", placeholder: "Image Url" %>
    <h2>2.写真のタイトルを記入ください</h2>
      <%= f.text_field :title, placeholder: "Title" %>
    <h2>3.テーマを選択してください</h2>
      <%= f.collection_select(:theme_id, Theme.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>4.登山を開始した地域を選択してください</h2>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>5.登山した山の情報を選択してください</h2>
      <%= f.collection_select(:mountain_name_id, MountainName.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>6.登山時間を選択してください</h2>
      <%= f.collection_select(:climbing_time_id, ClimbingTime.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>7.体力度を選択してください</h2>
      <%= f.collection_select(:stamina_id, Stamina.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>8.眺望度を選択してください</h2>
      <%= f.collection_select(:mountain_view_id, MountainView.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>
    <h2>9.危険度を選択してください</h2>
      <%= f.collection_select(:danger_id, Danger.all, :id, :name, {}, {class:"select-box", id:"tweet-prefecture"}) %>

    <h2></h2>
      <%= f.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/tweets/search.html.erb
<div class='search-list'>
<h3>検索結果</h3>
      <br>同じ山でも時期や天候で大きく変化します。<br>
          常に万全の準備で登山を楽しんでください。
</div>

<div class='search-contents'>
<table>
  <tr>
    <th>投稿者名</th>
    <th>登山時間</th>
    <th>眺望度</th>
    <th>体力度</th>
    <th>危険度</th>
    <th>投稿日時</th>
  </tr>
<%# 検索結果の個数で条件分岐 %>
<% if @results.length !=0 %>
  
  <% @results.each do |result| %>
    <table>
    <tr>
      <th>
      <%= result.user.nickname %>
      </th>
      <th>
      <%= result.climbing_time.name %>
      </th>
      <th>
      <%= result.mountain_view.name %>
      </th>
      <th>
      <%= result.stamina.name %>
      </th>
      <th>
      <%= result.danger.name %>
      </th>
      <th>
      <%= result.created_at.strftime('%Y/%m/%d') %>
      </th>
    </tr>
    </table>
  <% end %>
<% else %>
  該当する投稿はありません
<% end %>
<br>
<%= link_to 'トップページへ戻る', root_path %>
</div>

app/views/tweets/show.html.erb
<h2 class="name">
  <%= @tweet.title %>
</h2>

  <div class= 'tweet-contents'>
  <div class="tweet-img-content">
  <% if user_signed_in? && current_user.id == @tweet.user_id%>
    <%= link_to "編集する", edit_tweet_path(@tweet.id), class: :tweet__btn %>
    <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, class: :tweet__btn %>
  <% end %>
  <%= image_tag @tweet.image ,class:"tweet-box-img" %>
  </div>
    <div class='user-name'>
      <%= @tweet.user.nickname %>さんの登山情報
    </div>

    <table>
    <tr>
      <th>山の情報</th>
      <th>登山時間</th>
      <th>眺望度</th>
      <th>体力度</th>
      <th>危険度</th>
    </tr>
    <tr>
      <td> <%= @tweet.mountain_name.name %> </td>
      <td> <%= @tweet.climbing_time.name %> </td>
      <td> <%= @tweet.mountain_view.name %> </td>
      <td> <%= @tweet.stamina.name %> </td>
      <td> <%= @tweet.danger.name %> </td>
    </tr>
    </table>
    <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with model: [@tweet, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :text, "コメント一覧" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %> 
        <% else %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% if @comments %>
              <% @comments.each do |comment| %>
            <li class="comments_list">
             
              <%= comment.text %>
              <%= comment.created_at.strftime('%Y/%m/%d') %>
              <%#= link_to comment.user.name , user_path(comment.user.id), class: :comment_user %>
              <% end %>
             <% end %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
  </div>
  